name: aio_hutech
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12.3
  - keras=3.9.0
  - pytorch=2.5.1
  - torchvision
  - torchaudio
  - numpy=2.1.3
  - scipy=1.15.2
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - pandas=2.2.3

  - matplotlib=3.10.0
  - opencv-python=4.11.0
  - albumentations=2.0.5